# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 1.6.2
_src_path: gh:algorandfoundation/algokit-python-template
author_email: tamminakarthik01@gmail.com
author_name: karthik
contract_name: safesend_contracts
deployment_language: python
preset_name: starter
project_name: safesend

